### ISSUE TITLE
v2.0.1 doesn't work with UglifyJs

### ISSUE THREAD

**Issue by joeduncan** [marcuswestin/store.js#179]
The error is:
```
ERROR in bundle.js from UglifyJs
SyntaxError: Name expected [bundle.js:113484,4]
```
Downgrading to `v1.3.20` seems to work again

No idea what is causing this yet

**Comment by joeduncan** [comment]
It doesn't seem to like this line: https://github.com/marcuswestin/store.js/blob/eccd5cdcdce45a1e054de25eab2d2cdd2ed1e507/src/store-engine.js#L1

**Comment by hyperknot** [comment]
It is not related to Webpack, I run into the same error in Browserify + uglifyify.

```
Error: Uncaught, unspecified "error" event. (SyntaxError: Name expected while parsing file: ..node_modules/store/src/store-engine.js (line: 1, col: 4, pos: 4)

Error
    at new JS_Parse_Error (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)
    at js_error (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)
    at croak (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)
    at as_symbol (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2745:27)
    at vardefs (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2513:25)
    at var_ (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2527:27)
    at eval (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2270:30)
    at eval (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)
    at eval (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2909:23)
    at Object.parse (eval at <anonymous> (..node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2920:7))
    at Readable.emit (events.js:144:17)
    at Labeled.<anonymous> (..node_modules/read-only-stream/index.js:28:44)
    at emitOne (events.js:77:13)
    at Labeled.emit (events.js:169:7)
    at Labeled.<anonymous> (..node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:82:20)
    at Labeled.emit (events.js:169:7)
    at Deps.<anonymous> (..node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:77:13)
    at Deps.emit (events.js:169:7)
```

**Comment by hyperknot** [comment]
#180 fixes it for me

**Comment by joeduncan** [comment]
@hyperknot good to know 👍

**Comment by hyperknot** [comment]
@joeduncan I'm actually using 

```
"store": "marcuswestin/store.js#a08441",
```

In production now :-)

**Comment by joeduncan** [comment]
@hyperknot try 12153c87a7922e00e09c2eb7423a7b2720b86e11 - i missed the plugins ;)

**Comment by hyperknot** [comment]
@joeduncan thanks.

**Comment by marcuswestin** [comment]
Right, of course - I was originally building just for compiled builds and figures ES5/6 features would be kosher. I totally see why that's not the case. I'll review, pull, test and release shortly!
