### ISSUE TITLE
store.update doesn't new object if its null

### ISSUE THREAD

**Issue by ThaneshR** [marcuswestin/store.js#260]
```html
<html>
<head>
</head>
<body>
	<script type="text/javascript" src='./store.everything.min.js'></script>
	<script type="text/javascript">
		store.update('foo2', {}, function(foo2) {
			foo2.bar = 'cat';
		});
	</script>
</body>
</html>
```
I include store.everything.min.js in the folder.

I run this and I get the following console error on Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit)), Windows 10:

```
store.everything.min.js:2 Uncaught TypeError: t.charCodeAt is not a function
    at http://localhost/localstorage/store.everything.min.js:2:10614
    at Object._decompress (http://localhost/localstorage/store.everything.min.js:2:10713)
    at Object.decompress (http://localhost/localstorage/store.everything.min.js:2:10566)
    at Object.t (http://localhost/localstorage/store.everything.min.js:2:1415)
    at Object.(anonymous function) (http://localhost/localstorage/store.everything.min.js:2:14953)
    at e (http://localhost/localstorage/store.everything.min.js:2:14889)
    at Object.e (http://localhost/localstorage/store.everything.min.js:2:1700)
    at Object.(anonymous function) (http://localhost/localstorage/store.everything.min.js:2:14953)
    at e (http://localhost/localstorage/store.everything.min.js:2:14889)
    at Object.e (http://localhost/localstorage/store.everything.min.js:2:3181)
```

**Comment by cemalgultekin** [comment]
It's due to compress plugin being buggy. (didn't search through much though why it's buggy).
Simply change 
    e.exports = [*t("./compression"),*
with
    e.exports = [
in **store.everything.min.js**

**Comment by daweilv** [comment]
same error
